# goreleaser 配置文件

builds:
  - id: apidoc

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64

    main: ./cmd/apidoc

    binary: apidoc

    ldflags:
      - -s -w -X github.com/caixw/apidoc/v5/internal/vars.commitHash={{.Commit}} -X github.com/caixw/apidoc/v5/internal/vars.buildDate={{time "20060102"}}

archives:
  - builds:
      - binary
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
