# goreleaser 配置文件

builders:
  - id: binary
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/caixw/apidoc/v5/internal/vars.commitHash={{.Commit}} -X github.com/caixw/apidoc/v5/internal/vars.buildDate={{time "20060102"}}

