project_name: apidoc

release:
  github:
    owner: caixw
    name: apidoc
  name_template: '{{.Tag}}'

changelog:
  skip: true

builds:
  - id: apidoc

    goos:
    - darwin
    - linux
    - windows

    goarch:
    - amd64

    main: ./cmd/apidoc

    binary: apidoc

    ldflags:
      - -s -w -X github.com/caixw/apidoc/v5/internal/vars.commitHash={{.Commit}} -X github.com/caixw/apidoc/v5/internal/vars.buildDate={{time "20060102"}}

archives:
  - builds:
    - binary
    replacements:
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
