name: Go
on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
        go: ['1.13.x']
        
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: generate
        run: go generate -v ./...
        
      - name: Vet
        run: go vet -v ./...
        
      - name: Test
        run: |
          go test -v -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)

      - name: Upload Coverage report
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
