name: Release
on:
  create:
    tags:
      - 'v*'
      - '!v*-alpha'
      - '!v*-beta'

jobs:

  release:
    name: Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
        go: ['1.13.x']

    steps:

      - name: setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
